### ISSUE TITLE
关于预训练阶段使用的yelp和amazon

### ISSUE THREAD

**Issue by ABBlankSpace** [Tribleave/SCAPT-ABSA#7]
作者您好，请问预训练阶段用的yelp和amazon数据集是原始发布的数据集本身就带有aspect信息，还是您采取什么方法标注的，或是其他人的工作标注的呢？

**Comment by Tribleave** [comment]
您好，在yelp和amazon数据集中是包含aspect标注的。在本文使用中，构造语料的筛选条件之一是该句子中包含下游（也就是ABSA中）的aspect。

需要注意的是，这种标注的结果是有噪声的。然而因为数据集较大，本文没有人工地进行筛选。
